name: LambdaUtils
version: 1.0
main: pl.lambdathedev.lambdautils.LambdaUtils
api-version: 1.16
authors: [ LambdaTheDev ]
description: Basic plugin for basic commands and listeners.
website: https://github.com/LambdaTheDev/LambdaUtils
commands:
  ban:
  gamemode:
  kick:
  login:
  modifyrank:
  mute:
  register:
  setrank:
  rules:
  unban:
  unmute: